### ISSUE TITLE
Error in getting user profile 

### ISSUE THREAD

**Issue by nibinki** [messenger4j/messenger4j#84]
Hi

I add a new user as tester for my app . When that user sent a message , library throws following error . it seems error is from getting user profile . i tried for another user it works ..is there any permission needed ? my app is in development stage and not yet published 

INFO : com.chatbot.service.facebook.MessengerCallbackHandler - Received Messenger Platform callback - payload: {"object":"page","entry":[{"id":"1651896301510075","time":1524629086881,"messaging":[{"sender":{"id":"1670471212990771"},"recipient":{"id":"1651896301510075"},"timestamp":1524629086212,"message":{"mid":"mid.$cAAWEl9a32GppLD7oBFi-vlct6ukN","seq":1185928,"text":"Hi!","nlp":{"entities":{"greetings":[{"confidence":0.99991154670491,"value":"true"}]}}}}]}]} sha1=f7971344f120f49917c45a3ab9311a321d172767
INFO : com.chatbot.service.facebook.MessengerCallbackHandler - Received text message from senderId1670471212990771 at timestamp 2018-04-25T04:04:46.212Z with text Hi! with messageId mid.$cAAWEl9a32GppLD7oBFi-vlct6ukN to recipientId1651896301510075
java.lang.IllegalArgumentException
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.github.messenger4j.userprofile.UserProfileFactory.create(UserProfileFactory.java:48)
        at com.github.messenger4j.Messenger.doRequest(Messenger.java:203)
        at com.github.messenger4j.Messenger.queryUserProfile(Messenger.java:168)
        at com.chatbot.service.facebook.MessengerCallbackHandler.lambda$1(MessengerCallbackHandler.java:148)
        at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:151)
        at com.chatbot.service.facebook.MessengerCallbackHandler.handleMessage(MessengerCallbackHandler.java:132)
        at com.chatbot.service.facebook.MessengerCallbackHandler.lambda$0(MessengerCallbackHandler.java:117)
        at com.github.messenger4j.Messenger.onReceiveEvents(Messenger.java:151)
        at com.chatbot.service.facebook.MessengerCallbackHandler.handleCallback(MessengerCallbackHandler.java:114)
        at sun.reflect.GeneratedMethodAccessor220.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)

**Comment by maxgrabenhorst** [comment]
Hi, this is a known issue which was fixed with the latest version. So please upgrade.

Max


Von meinem iPhone gesendet

**Comment by nibinki** [comment]
i am using messenger4j 1.0.0.M3

**Comment by maxgrabenhorst** [comment]
Okay thanks. I will investigate.

Von meinem iPhone gesendet

**Comment by maxgrabenhorst** [comment]
When I first answered I was on vacation and forgot everything ;)
It's not a library issue rather than a permission issue. I also had this in the past.
Try to give the administrator role to the test user and it should work. 
I have not had a deep look at the permission system so far...

**Comment by tomschuyten** [comment]
Hi, seems that bug is still in version 1.0.0 ? I cannot get app reviewed.... nor can I add the reviewer as admin, because he's not a fb friend....
